using UnityEngine;
using UnityEngine.Networking;
using System.Collections;

public class AISyncService : MonoBehaviour
{
    public static AISyncService Instance { get; private set; }

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    private static void InitializeOnLoad()
    {
        if (Instance == null)
        {
            GameObject go = new GameObject("AISyncService_AutoGenerated");
            DontDestroyOnLoad(go);
            Instance = go.AddComponent<AISyncService>();
            Debug.Log("[AISyncService] Auto-instantiated global sync service at startup.");
        }
    }

    [Header("Web Service Settings")]
    [SerializeField] private string configUrl = "https://81dnn-rl.azurewebsites.net/api/aiconfig";

    [Header("Scriptable Objects to Update")]
    [SerializeField] private EnemySO[] enemyConfigs;

    public EnemySO[] EnemyConfigs => enemyConfigs;

    private void Awake()
    {
        Instance = this;
    }

    private void Start()
    {
        if (enemyConfigs == null || enemyConfigs.Length == 0)
        {
            enemyConfigs = Resources.FindObjectsOfTypeAll<EnemySO>();
            Debug.Log($"[AISyncService] Auto-discovered {enemyConfigs.Length} EnemySO configurations in memory.");
        }

        if (configUrl.Contains("127.0.0.1") || configUrl.Contains("localhost"))
        {
            configUrl = "https://81dnn-rl.azurewebsites.net/api/aiconfig";
            Debug.Log($"[AISyncService] Auto-redirected localhost URL to Azure: {configUrl}");
        }

        if (enemyConfigs != null)
        {
            foreach (var enemySO in enemyConfigs)
            {
                if (enemySO != null)
                {
                    StartCoroutine(FetchConfigForRole(enemySO));
                }
            }
        }
    }

    private System.Collections.Generic.Dictionary<string, AiGenerationConfigData[]> cachedConfigs = 
        new System.Collections.Generic.Dictionary<string, AiGenerationConfigData[]>();

    public AiGenerationConfigData[] GetConfigsForRole(string role)
    {
        if (cachedConfigs.TryGetValue(role, out var configs))
        {
            return configs;
        }
        return null;
    }

    private IEnumerator FetchConfigForRole(EnemySO enemySO)
    {
        string enemyType = enemySO.defaultMode.ToString();
        string requestUrl = $"{configUrl}/all?playerId={AIEvaluationTracker.GetPlayerId()}&enemyType={enemyType}";
        
        using (UnityWebRequest webRequest = UnityWebRequest.Get(requestUrl))
        {
            yield return webRequest.SendWebRequest();

            if (webRequest.result == UnityWebRequest.Result.Success)
            {
                string jsonResponse = webRequest.downloadHandler.text;
                Debug.Log($"[AISyncService] Successfully loaded latest AI configs population for {enemyType}: {jsonResponse}");
                
                string wrappedJson = "{\"items\":" + jsonResponse + "}";
                AiGenerationConfigListWrapper wrapper = JsonUtility.FromJson<AiGenerationConfigListWrapper>(wrappedJson);
                if (wrapper != null && wrapper.items != null && wrapper.items.Length > 0)
                {
                    cachedConfigs[enemyType] = wrapper.items;
                    
                    // Apply candidate 0 to the shared ScriptableObject as a default fallback
                    ApplyConfig(enemySO, wrapper.items[0]);
                }
            }
            else
            {
                Debug.LogWarning($"[AISyncService] Failed to load config for {enemyType} from server. Using local assets. Error: {webRequest.error}");
            }
        }
    }

    private void ApplyConfig(EnemySO enemySO, AiGenerationConfigData data)
    {
        enemySO.maxHealth = data.base_health;
        enemySO.minSpread = data.min_spread;
        enemySO.maxSpread = data.max_spread;
        enemySO.pushProbability = data.push_probability;
        enemySO.coverProbability = data.cover_probability;
        enemySO.peekCooldown = data.peek_cooldown;
        enemySO.peekDuration = data.peek_duration;
        enemySO.flankProbability = data.flank_probability;
        enemySO.configId = data.id;

        Debug.Log($"[AISyncService] Applied dynamic DNA (Gen {data.generation_number}, ConfigID {data.id}) to {enemySO.name} ({enemySO.defaultMode}): Health={enemySO.maxHealth}, MinSpread={enemySO.minSpread}, MaxSpread={enemySO.maxSpread}, PushWeight={enemySO.pushProbability}, PeekCooldown={enemySO.peekCooldown}, PeekDuration={enemySO.peekDuration}, FlankWeight={enemySO.flankProbability}");
    }

    [System.Serializable]
    public class AiGenerationConfigData
    {
        public int id;
        public int generation_number;
        public int base_health;
        public float min_spread;
        public float max_spread;
        public float push_probability;
        public float cover_probability;
        public float peek_cooldown;
        public float peek_duration;
        public float flank_probability;
    }

    [System.Serializable]
    private class AiGenerationConfigListWrapper
    {
        public AiGenerationConfigData[] items;
    }
}
